<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <title>ri Mai</title>
    <link rel="stylesheet" href="../../assets/styles/css/style.css">
</head>
<body>
<header>
    <nav class="nav-bar">
        <ul>
            <li><a>ACCUEIL</a></li>
            <li><a>MARCHÉ</a></li>
            <li><a>À PROPOS DE NOUS</a></li>
            <li><a>S’identifier</a></li>
            <li><a>S’INSCRIRE</a></li>
        </ul>
    </nav>
</header>
</body>
</html>

